### ISSUE TITLE
is this good for integration with Loco?

### ISSUE THREAD

**Issue by jondot** [m1guelpf/flysystem#2]
Hi,
We've been looking for the `paperclip` equivalent from Rails, to integrate into [Loco](https://github.com/loco-rs/loco) as a standard file upload/handling framework capability.

This looks like a good fit. Is this stable for integration at this point?

(PS we already did a similar integration with [`sidekiq-rs`](https://github.com/film42/sidekiq-rs) which gave us background jobs, just like with rails)

**Comment by m1guelpf** [comment]
Hey! This wasn't great for integrating into frameworks due to it being generic over the adapter (which defeats the purpose of the library, since you can't actually have users select a backend and not worry about it throughout the code.

This has however been fixed as of `0.2.0`, and should be now stable and ready to integrate!
